### ISSUE TITLE
How are cross `DAG_VIEW` dependencies tracked / visualized?

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/developers#30]
I just read this from the `README`:

>  - `DAG_VIEW=[core|wallet|zf]`: The DAG to render (default: `core`).

My immediate question is: what about dependencies across these views? Can `wallet` or `zf` issues depend on issues in `core`, or not?

**Comment by str4d** [comment]
Yes they can, because ZenHub treats GitHub repositories as globally unique. We already have this on a smaller scale with edges between repositories in the core team ZenHub team and the wallet team Zenhub team. And as another example, an ECC authentication token is being used to render the public graphs, including the ZF-specific graph.

For visualisation, we currently prune all issues from "unknown" nodes, because the `DAG_VIEW` explicitly defines which repositories should be shown in the graph. But anyone with the necessary permissions could create a graph with whatever repositories they want in it (and no permissions are needed if they only include public repositories, beyond having accounts on GitHub and Zenhub).
