### ISSUE TITLE
Some graphs are not rendering correctly after the graphql API change:

### ISSUE THREAD

**Issue by nuttycom** [zcash/developers#69]
```
Fetching graph
Traceback (most recent call last):
  File "./zcash-issue-dag.py", line 269, in <module>
    main()
  File "./zcash-issue-dag.py", line 62, in main
    dg = nx.compose_all([
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/networkx/algorithms/operators/all.py", line 179, in compose_all
    raise ValueError("cannot apply compose_all to an empty list")
ValueError: cannot apply compose_all to an empty list
Error: Process completed with exit code 1.
```

**Comment by str4d** [comment]
The only one that fails in this way is the `tfl` DAG, and AFAICT it's because no ZenHub workspace contains the `Electric-Coin-Company/zebra-tfl` repo. The ZenHub GraphQL query requires querying repos within the context of a ZenHub workspace.

We could either remove this render entirely, or add that repo to one of our workspaces in order to cause it to appear. I'm also going to alter the script to return a better error in this case.

**Comment by str4d** [comment]
Ah, it's not just that; none of the TFL repos were being counted as part of the ECC Core workspace (when some of them are). That's also an easy fix.
